language: generic 
sudo: required

services:
  - docker


before_install:
  - docker build -t waterchiller/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true waterchiller/docker-react npm run test